[package]
name = "startlang"
version = "0.0.1"
edition = "2021"

[build-dependencies]
cc="*"

[dev-dependencies]
pretty_assertions = "1.4.0"

[dependencies]
color-print = "0.3.6"
tree-sitter = "0.22"
tree-sitter-start = { path = "./tree-sitter-start" }
