[package]
name = "start-lang"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Damour <jeremy.damour2@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

readme = "README.md"

[dependencies]
stringreader = "0.1.1"
# num-bigint = "0.4"
# num-rational = "0.4"