Set DebugTyper.

Type N1 := ℕ.

Def long_number
    : N1 :=
  333_333_333_333_333_333_333_333_333_333_333_333_333_333_333_333_333_333_331.

Def a := (3 : ℕ).
Def n := 3 : ℕ.
Def n := ((a : ℕ)).

Type LongType_NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN :=
  N1.

Def c
  : LongType_NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN :=
  long_number.

$ long_number.

Def b := true.
Def c := '\\'.

?: b.
