name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy check
        run: cargo clippy --workspace --all-targets -- -D warnings

  coverage:
    name: Coverage (llvm-cov) + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profil: minimal

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Run coverage tests and generate junit report
        run: cargo llvm-cov nextest --lcov --output-path core.lcov --workspace --all-features
      - run: mv target/nextest/default/core-test-results.xml .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./core.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: start974/start-lang

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./core-test-results.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
